config/routes.rb
Rails.application.routes.draw do
  get 'game/play'

  get 'slangs/index'

  post 'game/answer'

  get 'game/over'

  get 'game/win'

  devise_for :users, controllers: {
  registrations: "users/registrations",
  sessions: "users/sessions",
  passwords: "users/passwords",
  omniauth_callbacks: "users/omniauth_callbacks"}


  resources :questions


  root 'slangs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/game_controller.rb
class GameController < ApplicationController
    before_action :authenticate_user!, except: [:index]

  @@ltu = 0
  @@q1 = Question.where(level: 1).to_a
  @@q2 = Question.where(level: 2).to_a
  @@q3 = Question.where(level: 3).to_a
  @@q4 = Question.where(level: 4).to_a
  @@q5 = Question.where(level: 5).to_a

  def play
    @user = current_user
    # @questions = Question.where(level: @user.level).to_a
    if @user.level >= 6
      redirect_to game_win_path
    end
    case @user.level
    when 1  
      @questions = @@q1 
      @question = @questions.sample
      @@q1.delete(@question)
      @@q1.compact!
    when 2  
      @questions = @@q2 
      @question = @questions.sample
      @@q2.delete(@question)
      @@q2.compact!
    when 3  
      @questions = @@q3 
      @question = @questions.sample
      @@q3.delete(@question)
      @@q3.compact!
    when 4  
      @questions = @@q4 
      @question = @questions.sample
      @@q4.delete(@question)
      @@q4.compact!
    when 5  
      @questions = @@q5 
      @question = @questions.sample
      @@q5.delete(@question)
      @@q5.compact!
    end


    @order = rand(1..3) 

  end


  def answer
    @notice=""

    @user = current_user
    if params[:answer].present?
      answer = params[:answer]
        if answer == "a"
          @@ltu += 1
            if @@ltu == 3
              
              up
              p @notice
              @@ltu = 0
            end
        else
          lose_life
        end
    end
    
    if @user.life>0
      redirect_to game_play_path, notice: @notice
    elsif @user.life==0
      redirect_to game_over_path # ruta game over
    end

  end


  def lose_life
    if @user.life > 0
      ull = @user
      ull.life-=1
      ull.save
    else 
      game_over
    end
  end

  def game_over
    @user=current_user
    @user.life=3 
    @user.save
  end

  def up
    @a = current_user
    @a.level += 1
    @a.save
    @notice="hola"
  end

end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/level/_q1.html.erb
<div class="question-form quest-lvl-one lvl-<%= @user.level %> ">
<%= form_tag(game_answer_path) do %>
	
<h2><%= @question.title %></h2>


<% case @order %>
<% when 1 %>
	<div class="cont-answer">
	<%= radio_button_tag(:answer, "a") %>
	<%= label_tag(:a, @question.a) %><br>
	<%= radio_button_tag(:answer, "b") %>
	<%= label_tag(:b, @question.b) %><br>
	<%= radio_button_tag(:answer, "c") %>
	<%= label_tag(:c, @question.c) %>
	</div>

<% when 2 %>
	<div class="cont-answer">
	<%= radio_button_tag(:answer, "b") %>
	<%= label_tag(:b, @question.b) %><br>
	<%= radio_button_tag(:answer, "a") %>
	<%= label_tag(:a, @question.a) %><br>
	<%= radio_button_tag(:answer, "c") %>
	<%= label_tag(:c, @question.c) %>
	</div>

<% when 3 %>
	<div class="cont-answer">
	<%= radio_button_tag(:answer, "c") %>
	<%= label_tag(:c, @question.c) %><br>
	<%= radio_button_tag(:answer, "b") %>
	<%= label_tag(:b, @question.b) %><br>
	<%= radio_button_tag(:answer, "a") %>
	<%= label_tag(:a, @question.a) %>
	</div>
<% end %>


	<%= submit_tag "enviar" %>
<% end -%>
</div>

app/views/game/level/_q2.html.erb
<%= form_tag(game_answer_path) do %>
	
<h2><%= @questions.first.title %></h2>


<% case @order %>
<% when 1 %>

	<%= radio_button_tag(:answer, "a") %>
	<%= label_tag(:a, @questions.first.a) %>
	<%= radio_button_tag(:answer, "b") %>
	<%= label_tag(:b, @questions.first.b) %>
	<%= radio_button_tag(:answer, "c") %>
	<%= label_tag(:c, @questions.first.c) %>


<% when 2 %>

	<%= radio_button_tag(:answer, "b") %>
	<%= label_tag(:b, @questions.first.b) %>
	<%= radio_button_tag(:answer, "a") %>
	<%= label_tag(:a, @questions.first.a) %>
	<%= radio_button_tag(:answer, "c") %>
	<%= label_tag(:c, @questions.first.c) %>


<% when 3 %>

	<%= radio_button_tag(:answer, "c") %>
	<%= label_tag(:c, @questions.first.c) %>
	<%= radio_button_tag(:answer, "b") %>
	<%= label_tag(:b, @questions.first.b) %>
	<%= radio_button_tag(:answer, "a") %>
	<%= label_tag(:a, @questions.first.a) %>
<% end %>


	<%= submit_tag "enviar" %>
<% end -%>